### ISSUE TITLE
Error: Class 'libphonenumber\geocoding\Locale' not found

### ISSUE THREAD

**Issue by jiripudil** [iPublikuj/form-phone#2]
The `Locale` class has been removed in giggsey/libphonenumber-for-php@b2b2842 (7.5.0+).

I will try to take a look at it and send a PR, but don't know when, so I'm filing an issue in case someone finds the time sooner than me

**Comment by brychta-v** [comment]
Could you please create new release version with this fix?
When I install via Composer v1.0.3 of iPublikuj/form-phone it auto-pulls giggsey/libphonenumber-for-php v7.7.2, so I get this error by default.
